
name: Python Flask Docker build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
   
    - name: Build Docker Image
      run: docker build -t devops1608/action:latest .
   
    - name: Push Docker Image
      run: docker push devops1608/action:latest
      
    - name: Log out from Docker Hub  
      run: docker logout
